### PR TITLE
2.2.13

### PR DESCRIPTION
**Pull request by etrikp**
Simple fix for the ubuntu cloud agent init script.  This script could be better in general but I would hate for the 2.2.13 release to go out with this broken still.  It makes things a pain for ubuntu based installs.   The other two changes are consistency/formatting tweaks.  I think it would be a great idea to standardize on basic coding standards, such as soft tabs vs real tabs,  stripping trailing white space, etc, take those commits with a grain of salt as I'm mainly concerned with the agent init script.

### CODE REVIEW

**Comment by ke4qqq** [comment]
@etrikp  Have you signed the CloudStack CLA: 
More details here: http://cloudstack.org/about-cloudstack/contribute.html

I'll need that to be signed before I can merge this request. 

Thanks! 
David

**Comment by etrikp** [comment]
Completed, I got the following notice:

Your e-Signing of Cloud.com Individual Contributor Agreement has been verified. Copies of the signed document are being sent to you and Peder Ulander (Cloud.com).

**Comment by ke4qqq** [comment]
awesome, thanks! I'll work on getting this merged shortly.

**Comment by ke4qqq** [comment]
This was committed  already - but didn't make it into 2.2.13 - it will hit 2.2.14 and 3.0 
See:
http://bugs.cloud.com/show_bug.cgi?id=12194

Thanks for the patch

**Pull request closed without merging**
